In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

from helper import util_three_class

# 0. Get folder names for train and validation

In [2]:
folder_train = '/path/to/9_FINAL/data/machine_learning/one_hot_encoded/three_class/train/downsampled_to_subclass/train_'

In [3]:
folder_validation = '/path/to/9_FINAL/data/machine_learning/one_hot_encoded/three_class/validation/validation_'

# 1. Logistic Regression

## 1.1 Only one hot encoded columns

In [4]:
lr = LogisticRegression(random_state=42)

In [8]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   456    154    111]
 [  3904  13524   4697]
 [151658 553413 594943]]
Micro 0.46030796909725896 and Macro 0.22601897140685925
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   423    177    121]
 [  2907  13999   5219]
 [106877 569126 624011]]
Micro 0.48261569629439244 and Macro 0.2335759881929915
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   421    169    131]
 [  3094  14194   4837]
 [121199 562768 616041]]
Micro 0.4767389296173274 and Macro 0.23181812141083247
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   468    144    109]
 [  3897  13614   4614]
 [148664 563089 588255]]
Micro 0.45533142735328314 and Macro 0.22435194420695445
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   444    176    104]
 [  3806  13307   5012]
 [149719 545262 605027]]
Micro 0.46775879781412505 and Macro 0.2283479754688222
----------------------------------
---------------------
Overall Micro: 0.46855056403527734
Overall Macro: 0.228822600137292


## 1.2 Only one hot encoded columns + frequencies

In [9]:
lr = LogisticRegression(random_state=42)

In [10]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   381    260     80]
 [  2393  16168   3564]
 [112469 722658 464887]]
Micro 0.3639357150416522 and Macro 0.19159296560251907
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   390    258     73]
 [  2192  16398   3535]
 [ 96294 735352 468368]]
Micro 0.36674780400042334 and Macro 0.19294380397227293
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   359    254    108]
 [  2158  15973   3994]
 [103892 674863 521253]]
Micro 0.4063827149481349 and Macro 0.2075387486234128
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   395    238     88]
 [  2336  16049   3740]
 [ 97485 722286 480237]]
Micro 0.37546169116168526 and Macro 0.1961274597222892
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   376    224    124]
 [  2309  14411   5405]
 [ 96615 608640 594753]]
Micro 0.46077542772952784 and Macro 0.22604534016743924
----------------------------------
---------------------
Overall Micro: 0.39466067057628473
Overall Macro: 0.20284966361758663


# 2. Naive Bayes

## 2.1 Only one hot encoded columns

In [12]:
nb = MultinomialNB()

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   301    265    155]
 [  2647  15064   4414]
 [206854 580161 512999]]
Micro 0.3994103684441286 and Macro 0.2053752891077639
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   334    252    135]
 [  2285  15654   4186]
 [185691 611652 502671]]
Micro 0.39207399120088293 and Macro 0.2026937774576805
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   304    212    205]
 [  2275   9066  10784]
 [196815 283934 819259]]
Micro 0.6263949007222264 and Macro 0.27656782474969305
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   319    267    135]
 [  2686  15246   4193]
 [211670 596961 491377]]
Micro 0.383218405054526 and Macro 0.19942970158757936
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   319    192    213]
 [  2348   8873  10904]
 [197219 276834 825955]]
Micro 0.6313206945270728 and Macro 0.27792265619934553
----------------------------------
---------------------
Overall Micro: 0.48648367198976733
Overall Macro: 0.23239784982041245


## 2.2 Only one hot encoded columns + frequencies

In [14]:
nb = MultinomialNB()

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    108     109     504]
 [    353     985   20787]
 [   6871   24949 1268194]]
Micro 0.9595021393042348 and Macro 0.34907022635840956
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    129     122     470]
 [    424    1561   20140]
 [   8312   36976 1254726]]
Micro 0.949772462694465 and Macro 0.3508961573979661
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    117     120     484]
 [    401    1412   20312]
 [   8326   38766 1252916]]
Micro 0.9482868101846462 and Macro 0.347775514670927
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    133     134     454]
 [    435    1927   19763]
 [   8221   44134 1247653]]
Micro 0.944709695854569 and Macro 0.3520400323611556
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    102     149     473]
 [    394    1579   20152]
 [   7852   38804 1253352]]
Micro 0.948729152130578 and Macro 0.3489164390759447
----------------------------------
---------------------
Overall Micro: 0.9502000520336985
Overall Macro: 0.3497396739728806


# 3. XGBoost

## 3.1 Only one hot encoded columns

In [17]:
xg = xgb.XGBRFClassifier(random_state=42)

In [18]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   454    160    107]
 [  3508  14094   4523]
 [136548 593487 569979]]
Micro 0.4418661082805437 and Macro 0.21976047597011306
----------------------------------
[[   458    181     82]
 [  3790  14413   3922]
 [154094 626110 519810]]
Micro 0.4041856281087946 and Macro 0.20642297606105742
----------------------------------
[[   457    157    107]
 [  4372  13724   4029]
 [180787 584608 534613]]
Micro 0.4148560612131044 and Macro 0.21020872375575528
----------------------------------
[[   495    131     95]
 [  4390  13479   4256]
 [171046 598086 530876]]
Micro 0.4118746286438261 and Macro 0.20889136849739753
----------------------------------
[[   455    136    133]
 [  3978  11235   6912]
 [163711 459532 676765]]
Micro 0.5204304017743414 and Macro 0.24441656672765202
----------------------------------
---------------------
Overall Micro: 0.43864256560412207
Overall Macro: 0.21794002220239506


## 3.2 Only one hot encoded columns + frequencies

In [19]:
xg = xgb.XGBRFClassifier(random_state=42)

In [20]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg)

[[   481    105    135]
 [  4404  11871   5850]
 [171497 489977 638540]]
Micro 0.49203392649259936 and Macro 0.23582878241088223
----------------------------------
[[   461    163     97]
 [  3622  13843   4660]
 [143710 603156 553148]]
Micro 0.42895846877220567 and Macro 0.21498826186763995
----------------------------------
[[   462    128    131]
 [  3736   9203   9186]
 [158926 355514 785568]]
Micro 0.6011494843724251 and Macro 0.2677292588013783
----------------------------------
[[   491    131     99]
 [  4050  13518   4557]
 [150892 599989 549127]]
Micro 0.4256977716361745 and Macro 0.21375024671192
----------------------------------
[[   471    156     97]
 [  3967  13518   4640]
 [156018 584857 559133]]
Micro 0.4332456191409956 and Macro 0.21645737978226667
----------------------------------
---------------------
Overall Micro: 0.47621705408288006
Overall Macro: 0.22975078591481743


# 4. Random Forest

## 4.1 Only one hot encoded columns

In [23]:
rf = RandomForestClassifier(random_state=42)

In [24]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   461    154    106]
 [  3787  13776   4562]
 [166390 599153 534471]]
Micro 0.4147891689218814 and Macro 0.20998985757838387
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   460    149    112]
 [  3520  13346   5259]
 [159534 559601 580879]]
Micro 0.44954492538893004 and Macro 0.2221166065349994
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   448    167    106]
 [  3520  13942   4663]
 [175294 577505 547209]]
Micro 0.42453588982608814 and Macro 0.21378471784828013
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   474    153     94]
 [  3857  13819   4449]
 [171337 592841 535830]]
Micro 0.4158607072284621 and Macro 0.21054058041335974
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   441    180    103]
 [  3591  13873   4661]
 [152252 594281 553475]]
Micro 0.4292141932196753 and Macro 0.21510753001859131
----------------------------------
---------------------
Overall Micro: 0.42678897691700735
Overall Macro: 0.21430785847872288


## 4.2 Only one hot encoded columns + frequencies

In [25]:
rf = RandomForestClassifier(random_state=42)

In [26]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   455    136    130]
 [  4149  12598   5378]
 [187573 536193 576248]]
Micro 0.4454749557776333 and Macro 0.2204309215475142
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   472    147    102]
 [  4135  12632   5358]
 [181292 539501 579221]]
Micro 0.44776091196347306 and Macro 0.22123295185546596
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   472    126    123]
 [  4110   9122   8893]
 [192629 362025 745354]]
Micro 0.5706963882635574 and Macro 0.25892324116061544
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   492    134     95]
 [  4332  12922   4871]
 [184881 569087 546040]]
Micro 0.42291439569294875 and Macro 0.21264219972925102
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   450    145    129]
 [  4039  11982   6104]
 [178545 508458 613005]]
Micro 0.4727925996536285 and Macro 0.22928388710589176
----------------------------------
---------------------
Overall Micro: 0.47192785027024825
Overall Macro: 0.22850264027974765


# 5. MLPClassifier

## 5.1 Only one hot encoded columns

In [28]:
nnet = MLPClassifier(random_state=42)

In [29]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   428    180    113]
 [  3557  14241   4327]
 [157814 617280 524920]]
Micro 0.40789577128343135 and Macro 0.2075694878106615
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   422    176    123]
 [  3251  13513   5361]
 [152141 554560 593313]]
Micro 0.4590417731279198 and Macro 0.22536686730811326
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   395    209    117]
 [  2970  14528   4627]
 [142313 590313 567382]]
Micro 0.4401884108147989 and Macro 0.2192861838676514
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   436    181    104]
 [  3515  14338   4272]
 [160262 611119 528627]]
Micro 0.41077926966997114 and Macro 0.20878055004340904
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   398    218    108]
 [  3166  14393   4566]
 [142907 609014 548087]]
Micro 0.4255017738122866 and Macro 0.2138754530698199
----------------------------------
---------------------
Overall Micro: 0.4286813997416816
Overall Macro: 0.214975708419931


## 5.2 Only one hot encoded columns + frequencies

In [30]:
nnet = MLPClassifier(random_state=42)

In [31]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   449    159    113]
 [  3610  14083   4432]
 [146373 575938 577703]]
Micro 0.4476928775531802 and Macro 0.22192668159488207
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   428    172    121]
 [  2971  14019   5135]
 [113380 561243 625391]]
Micro 0.4836777890328531 and Macro 0.23401923017305173
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   490     71    160]
 [  4851   7135  10139]
 [176765 249102 874141]]
Micro 0.6665633546861558 and Macro 0.2856475394073145
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   480    142     99]
 [  3776  13792   4557]
 [142683 573443 583882]]
Micro 0.45216932480833105 and Macro 0.22336609615527056
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   402    237     85]
 [  2740  15261   4124]
 [134277 627043 538688]]
Micro 0.41905587678789163 and Macro 0.21211610612240575
----------------------------------
---------------------
Overall Micro: 0.4938318445736824
Overall Macro: 0.23541513069058495


# 6. DecisionTreeClassifier

## 6.1 Only one hot encoded columns

In [33]:
dt = DecisionTreeClassifier(random_state=42)

In [34]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   388    212    121]
 [  3578  14410   4137]
 [169154 643301 487559]]
Micro 0.3797506916831713 and Macro 0.19701506762337595
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   386    199    136]
 [  3184  13672   5269]
 [155601 583544 560869]]
Micro 0.43460910451597295 and Macro 0.2166724100825592
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   375    221    125]
 [  3300  14132   4693]
 [169571 603088 527349]]
Micro 0.4096113403293183 and Macro 0.20805238567517947
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   385    213    123]
 [  3358  14314   4453]
 [157479 623517 519012]]
Micro 0.4034541982713134 and Macro 0.20577919836142544
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   382    224    118]
 [  3348  14120   4657]
 [147366 615995 536647]]
Micro 0.4166353581679653 and Macro 0.21039111008614783
----------------------------------
---------------------
Overall Micro: 0.4088121385935482
Overall Macro: 0.20758203436573758


## 6.2 Only one hot encoded columns + frequencies

In [35]:
dt = DecisionTreeClassifier(random_state=42)

In [37]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   365    215    141]
 [  3904  12797   5424]
 [184277 576207 539530]]
Micro 0.41780082548417824 and Macro 0.21018131323555864
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   385    203    133]
 [  3895  12661   5569]
 [180458 565784 553772]]
Micro 0.42847920414858714 and Macro 0.21397287027175269
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   369    187    165]
 [  3671   9254   9200]
 [174260 390740 735008]]
Micro 0.5628973416567512 and Macro 0.2556667804992823
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   394    196    131]
 [  3937  13187   5001]
 [171245 613324 515439]]
Micro 0.3999080775353894 and Macro 0.20378483415306936
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   362    210    152]
 [  3761  12235   6129]
 [171593 546139 582276]]
Micro 0.4496880615213889 and Macro 0.22095826224064377
----------------------------------
---------------------
Overall Micro: 0.45175470206925894
Overall Macro: 0.22091281208006136
