In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

from helper import util_three_class

# 0. Get folder names for train and validation

In [2]:
folder_train = '/path/to/9_FINAL/data/machine_learning/one_hot_encoded/three_class/train/downsampled_to_types/train_'

In [3]:
folder_validation = '/path/to/9_FINAL/data/machine_learning/one_hot_encoded/three_class/validation/validation_'

# 1. Logistic Regression

## 1.1 Only one hot encoded columns

In [4]:
lr = LogisticRegression(random_state=42)

In [5]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   461    155    105]
 [  3761  13533   4831]
 [151616 541649 606749]]
Micro 0.46924315498238667 and Macro 0.22917812897326487
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   447    166    108]
 [  3695  13637   4793]
 [144380 545722 609912]]
Micro 0.47170222094552705 and Macro 0.22997411150460453
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   432    159    130]
 [  3750  13497   4878]
 [157804 526312 615892]]
Micro 0.4761077186144503 and Macro 0.23152838286680896
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   459    148    114]
 [  3766  13512   4847]
 [143910 547975 608123]]
Micro 0.47026656002854433 and Macro 0.22940295355913146
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   433    183    108]
 [  3578  13706   4841]
 [138721 556392 604895]]
Micro 0.46795231835338214 and Macro 0.22858533459481026
----------------------------------
---------------------
Overall Micro: 0.4710543945848581
Overall Macro: 0.22973378229972402


## 1.2 Only one hot encoded columns + frequencies

In [6]:
lr = LogisticRegression(random_state=42)

In [7]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   372    272     77]
 [  2312  16272   3541]
 [108309 731161 460544]]
Micro 0.36072449087582964 and Macro 0.19034692327054747
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   391    261     69]
 [  2279  16197   3649]
 [101242 726411 472361]]
Micro 0.3696150764253208 and Macro 0.19390979379028753
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   364    268     89]
 [  2230  16252   3643]
 [114396 719243 466369]]
Micro 0.36510831883185896 and Macro 0.1920034712327933
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   371    296     54]
 [  1963  17359   2803]
 [ 88838 835061 376109]]
Micro 0.2977191738468493 and Macro 0.16526065244456228
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   373    266     85]
 [  2255  16169   3701]
 [ 98843 730808 470357]]
Micro 0.3680662384520776 and Macro 0.19318833523248688
----------------------------------
---------------------
Overall Micro: 0.3522466596863873
Overall Macro: 0.18694183519413549


# 2. Naive Bayes

## 2.1 Only one hot encoded columns

In [8]:
nb = MultinomialNB()

In [9]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   306    264    151]
 [  2559  15218   4348]
 [216807 585500 497707]]
Micro 0.38797076032233185 and Macro 0.20131632536264296
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   341    239    141]
 [  2283  15236   4606]
 [177585 589183 533246]]
Micro 0.4148761017794778 and Macro 0.21087654334715591
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   312    255    154]
 [  2362  15122   4641]
 [208547 570319 521142]]
Micro 0.40561997015543666 and Macro 0.20784040591434652
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   317    261    143]
 [  2390  15127   4608]
 [187910 591398 520700]]
Micro 0.40529340350484633 and Macro 0.2073018465060835
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   315    246    163]
 [  2243  15208   4674]
 [170240 597413 532355]]
Micro 0.4141626797151922 and Macro 0.21035303671079061
----------------------------------
---------------------
Overall Micro: 0.405584583095457
Overall Macro: 0.2075376315682039


## 2.2 Only one hot encoded columns + frequencies

In [10]:
nb = MultinomialNB()

In [11]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    110     125     486]
 [    391    1289   20445]
 [   7843   31681 1260490]]
Micro 0.9539097107781624 and Macro 0.34917866856255947
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    126     120     475]
 [    392    1324   20409]
 [   7436   31607 1260971]]
Micro 0.9543118697367824 and Macro 0.3512767222563329
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    115     107     499]
 [    386    1213   20526]
 [   8040   32589 1259379]]
Micro 0.9530205147355642 and Macro 0.348078236010231
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    122     123     476]
 [    386    1360   20379]
 [   7194   30066 1262748]]
Micro 0.955683696008781 and Macro 0.3523836316201496
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[     98     121     505]
 [    367    1312   20446]
 [   7307   30069 1262632]]
Micro 0.9555394120452929 and Macro 0.34980810469496504
----------------------------------
---------------------
Overall Micro: 0.9544930406609164
Overall Macro: 0.35014507262884764


# 3. XGBoost

## 3.1 Only one hot encoded columns

In [12]:
xg = xgb.XGBRFClassifier(random_state=42)

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   462    155    104]
 [  3745  14008   4372]
 [159172 582747 558095]]
Micro 0.4328235792147317 and Macro 0.21671918200486096
----------------------------------
[[   468    170     83]
 [  4129  14048   3948]
 [158777 623590 517647]]
Micro 0.40228217649637904 and Macro 0.20553084793338208
----------------------------------
[[   445    157    119]
 [  3738  13947   4440]
 [166629 565624 567755]]
Micro 0.4400689720861108 and Macro 0.2193356359484767
----------------------------------
[[   479    137    105]
 [  4102  13611   4412]
 [157400 581582 561026]]
Micro 0.4347539486594892 and Macro 0.21714475113394574
----------------------------------
[[   442    187     95]
 [  3800  13901   4424]
 [150897 592753 556358]]
Micro 0.43141548935372453 and Macro 0.21594141833969163
----------------------------------
---------------------
Overall Micro: 0.4282688331620871
Overall Macro: 0.21493436707207142


## 3.2 Only one hot encoded columns + frequencies

In [14]:
xg = xgb.XGBRFClassifier(random_state=42)

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg)

[[   457    134    130]
 [  3808  13147   5170]
 [145001 550911 604102]]
Micro 0.466947371603949 and Macro 0.2279003068857409
----------------------------------
[[   465    145    111]
 [  3717  13290   5118]
 [146600 557104 596310]]
Micro 0.46117125017008603 and Macro 0.22605631202745569
----------------------------------
[[   456    135    130]
 [  3549  13295   5281]
 [151081 534228 614699]]
Micro 0.4750713230636185 and Macro 0.23093079759908516
----------------------------------
[[   476    128    117]
 [  3658  13330   5137]
 [138467 562024 599517]]
Micro 0.4636361987037118 and Macro 0.22691361464321427
----------------------------------
[[   445    171    108]
 [  3387  13652   5086]
 [127522 579798 592688]]
Micro 0.45869281411369484 and Macro 0.2252190383537288
----------------------------------
---------------------
Overall Micro: 0.46510379153101206
Overall Macro: 0.22740401390184495


# 4. Random Forest

## 4.1 Only one hot encoded columns

In [16]:
rf = RandomForestClassifier(random_state=42)

In [17]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf)

[[   114    428    179]
 [  1020  16263   4842]
 [ 49014 636915 614085]]
Micro 0.47659011535612233 and Macro 0.23086061073566091
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   125    434    162]
 [  1095  16114   4916]
 [ 51711 628964 619339]]
Micro 0.4804574936123248 and Macro 0.23219691520094551
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   125    428    168]
 [  1061  16132   4932]
 [ 53997 617173 628838]]
Micro 0.48765396634851615 and Macro 0.2346605044760529
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   108    458    155]
 [  1121  16119   4885]
 [ 50838 636837 612333]]
Micro 0.4751544766089077 and Macro 0.2301772862277456
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   112    436    176]
 [  1225  15926   4974]
 [ 55782 634054 610172]]
Micro 0.47337694096943206 and Macro 0.22945959669356322
----------------------------------
---------------------
Overall Micro: 0.4786465985790606
Overall Macro: 0.23147098266679364


## 4.2 Only one hot encoded columns + frequencies

In [18]:
rf = RandomForestClassifier(random_state=42)

In [19]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    72    458    191]
 [   752  16005   5368]
 [ 36121 618528 645365]]
Micro 0.5000090712547057 and Macro 0.23804350450360182
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    81    460    180]
 [   768  16266   5091]
 [ 38199 633294 628521]]
Micro 0.48748015663033123 and Macro 0.23416967030261338
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    74    452    195]
 [   696  15872   5557]
 [ 36517 603209 660282]]
Micro 0.5111886874893223 and Macro 0.2416841067666481
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    84    469    168]
 [   765  16143   5217]
 [ 36025 634992 628991]]
Micro 0.4877469471309759 and Macro 0.23423898345199823
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    72    463    189]
 [   765  15991   5369]
 [ 37768 626355 635885]]
Micro 0.4928333145608331 and Macro 0.2356070092930118
----------------------------------
---------------------
Overall Micro: 0.4958516354132336
Overall Macro: 0.23674865486357466


# 5. MLPClassifier

## 5.1 Only one hot encoded columns

In [20]:
nnet = MLPClassifier(random_state=42)

In [21]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   182    382    157]
 [  1337  15960   4828]
 [ 62640 614576 622798]]
Micro 0.48299895680570887 and Macro 0.23353775630079707
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   135    418    168]
 [   910  16017   5198]
 [ 45898 607155 646961]]
Micro 0.5012722434724763 and Macro 0.23934295782598755
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   210    344    167]
 [  2645  14687   4793]
 [116189 553514 630305]]
Micro 0.4877348520698429 and Macro 0.23487432348856072
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   167    391    163]
 [  1332  15952   4841]
 [ 56275 622668 621065]]
Micro 0.481673714559581 and Macro 0.23295591736871432
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   144    386    194]
 [  1196  15614   5315]
 [ 50551 603182 646275]]
Micro 0.5004569654921129 and Macro 0.23880186860450112
----------------------------------
---------------------
Overall Micro: 0.49082734647994447
Overall Macro: 0.23590256471771215


## 5.2 Only one hot encoded columns + frequencies

In [22]:
nnet = MLPClassifier(random_state=42)

In [23]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   324    240    157]
 [  2371  14923   4831]
 [ 85283 588152 626579]]
Micro 0.4851805935624329 and Macro 0.23459960624808304
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   302    273    146]
 [  1982  15365   4778]
 [ 79675 598124 622215]]
Micro 0.4821991745158218 and Macro 0.2337887985813771
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   308    179    234]
 [  2151   8737  11237]
 [ 85381 256119 958508]]
Micro 0.7314132927745617 and Macro 0.30410400935059967
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   320    254    147]
 [  1957  15322   4846]
 [ 73913 606357 619738]]
Micro 0.48030999641683814 and Macro 0.23329060701633142
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   285    267    172]
 [  1842  15082   5201]
 [ 65448 594225 640335]]
Micro 0.4956711118435326 and Macro 0.23809870243013087
----------------------------------
---------------------
Overall Micro: 0.5349548338226373
Overall Macro: 0.2487763447253044


# 6. DecisionTreeClassifier

## 6.1 Only one hot encoded columns

In [24]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   131    376    214]
 [  1209  15929   4987]
 [ 58932 648498 592584]]
Micro 0.46009706242535114 and Macro 0.22505637701072614
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   130    398    193]
 [  1318  15790   5017]
 [ 62265 642162 595587]]
Micro 0.4622613126105559 and Macro 0.22570336400288013
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   145    363    213]
 [  1239  15854   5032]
 [ 64721 630121 605166]]
Micro 0.469564290541511 and Macro 0.22843883696818054
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   117    402    202]
 [  1319  15785   5021]
 [ 60344 650702 588962]]
Micro 0.4572416910709723 and Macro 0.22380788016342754
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   118    391    215]
 [  1399  15635   5091]
 [ 64186 647226 588596]]
Micro 0.4568513452323267 and Macro 0.22358143994427546
----------------------------------
---------------------
Overall Micro: 0.4612031403761434
Overall Macro: 0.22531757961789797


## 6.2 Only one hot encoded columns + frequencies

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    95    396    230]
 [   986  15518   5621]
 [ 44428 639302 616284]]
Micro 0.47767488623134724 and Macro 0.23039166876327108
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   104    388    229]
 [  1011  15763   5351]
 [ 47257 651332 601425]]
Micro 0.4666344133166019 and Macro 0.22690050398265119
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    93    382    246]
 [   916  15465   5744]
 [ 45284 627516 627208]]
Micro 0.4858933790123475 and Macro 0.23310401284701054
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   103    387    231]
 [   972  15585   5568]
 [ 44028 656584 599396]]
Micro 0.46496741136965986 and Macro 0.22619502163336094
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   100    382    242]
 [   958  15519   5648]
 [ 45670 648557 605781]]
Micro 0.46974087146229715 and Macro 0.22772993330572103
----------------------------------
---------------------
Overall Micro: 0.4729821922784508
Overall Macro: 0.22886422810640297
