In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

from helper import util_three_class

# 0. Get folder names for train and validation

In [2]:
folder_train = '/path/to/9_FINAL/data/machine_learning/count_based/three_class/train/downsampled_to_subclass/train_'

In [3]:
folder_validation = '/path/to/9_FINAL/data/machine_learning/one_hot_encoded/three_class/validation/validation_'

# 1. Logistic Regression

## 1.1 Count columns

In [4]:
lr = LogisticRegression(random_state=42)

In [5]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    181     197     343]
 [    636    5498   15991]
 [  17887  179409 1102718]]
Micro 0.8378792918373826 and Macro 0.3277956356382909
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    124     213     384]
 [    412    5660   16053]
 [  10431  186370 1103213]]
Micro 0.8383328545726683 and Macro 0.32863254025003136
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    186     165     370]
 [    745    6009   15371]
 [  17091  196576 1086341]]
Micro 0.8258931068734721 and Macro 0.3259289781885111
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    116     201     404]
 [    486    5440   16199]
 [  10449  152388 1137171]]
Micro 0.8638345577062926 and Macro 0.3356575418552734
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    121     156     447]
 [    349    3073   18703]
 [   5988   74877 1219143]]
Micro 0.9240129507573381 and Macro 0.3518704545671067
----------------------------------
---------------------
Overall Micro: 0.8579905523494308
Overall Macro: 0.3339770300998427


## 1.2 Scaled count columns

In [4]:
lr = LogisticRegression(random_state=42)

In [5]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    702      19       0]
 [  20407    1694      24]
 [1156851  138856    4307]]
Micro 0.0050670516910330645 and Macro 0.009539870878799997
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    716       1       4]
 [  21893      70     162]
 [1254706    6711   38597]]
Micro 0.029771102006259167 and Macro 0.021207891692844153
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    716       1       4]
 [  21954      62     109]
 [1264339    5280   30389]]
Micro 0.023560423145713737 and Macro 0.01710220206715146
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    700      20       1]
 [  20777    1262      86]
 [1165204  122218   12586]]
Micro 0.010997434335157168 and Macro 0.012562418571242073
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    724       0       0]
 [  21956     164       5]
 [1288532   10915     561]]
Micro 0.0010953564897793185 and Macro 0.003948245432707088
----------------------------------
---------------------
Overall Micro: 0.014098273533588493
Overall Macro: 0.012872125728548952


## 1.3 Count columns + frequencies

In [6]:
lr = LogisticRegression(random_state=42)

In [7]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   561    111     49]
 [  9341   8963   3821]
 [458068 490097 351849]]
Micro 0.2731755438973134 and Macro 0.15392940159547516
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    262     202     257]
 [   1916    4279   15930]
 [  70125  122124 1107765]]
Micro 0.8408342530577688 and Macro 0.3262421925759681
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   296    216    209]
 [  2730   7029  12366]
 [118005 242603 939400]]
Micro 0.7156685469447118 and Macro 0.29694607829226033
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    377     145     199]
 [   2826    3690   15609]
 [ 100511  116170 1083327]]
Micro 0.8220060566018623 and Macro 0.3207463588720801
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    329     140     255]
 [   2626    5289   14210]
 [  80602  184526 1034880]]
Micro 0.7865536486559016 and Macro 0.3128920370287371
----------------------------------
---------------------
Overall Micro: 0.6876476098315115
Overall Macro: 0.2821512136729042


## 1.4 Scaled count columns + frequencies

In [6]:
lr = LogisticRegression(random_state=42)

In [7]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   119    376    226]
 [  1104  18436   2585]
 [ 41622 884117 374275]]
Micro 0.29695508217044886 and Macro 0.16388606914993564
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   275    133    313]
 [  4821  12343   4961]
 [164743 538578 596693]]
Micro 0.4606012729994104 and Macro 0.22457898133037416
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   254    200    267]
 [  3636  14301   4188]
 [127805 627182 545021]]
Micro 0.42300662053408766 and Macro 0.21210014493214432
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   286    202    233]
 [  4414  15058   2653]
 [147848 782348 369812]]
Micro 0.29115533535824817 and Macro 0.16088097913096563
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   268    250    206]
 [  4309  14221   3595]
 [132592 715581 451835]]
Micro 0.35251278104889644 and Macro 0.1854742609435623
----------------------------------
---------------------
Overall Micro: 0.36484621842221826
Overall Macro: 0.18938408709739643


# 2. Naive Bayes

## 2.1 Count encoded columns

In [8]:
nb = MultinomialNB()

In [9]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   185    143    393]
 [  5331  12472   4322]
 [247604 593980 458430]]
Micro 0.3561125137958665 and Macro 0.18704722914678643
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   173    121    427]
 [  3712  12006   6407]
 [135631 500422 663961]]
Micro 0.5111198463934203 and Macro 0.24039074693797366
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   202    102    417]
 [  4154  11223   6748]
 [150674 454800 694534]]
Micro 0.5336635788983516 and Macro 0.2475026515997177
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   201    141    379]
 [  5018  12917   4190]
 [237739 598034 464235]]
Micro 0.36085085731305194 and Macro 0.18911978905824237
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   184    116    424]
 [  4524   6228  11373]
 [213091 219204 867713]]
Micro 0.6607857085081759 and Macro 0.282739724947855
----------------------------------
---------------------
Overall Micro: 0.4845065009817732
Overall Macro: 0.22936002833811503


## 2.2 Scaled Count encoded columns

In [8]:
nb = MultinomialNB()

In [9]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   331    358     32]
 [  6441  14831    853]
 [416522 704686 178806]]
Micro 0.14662776106315106 and Macro 0.094404969591804
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   570    121     30]
 [ 10018  11244    863]
 [598283 520147 181584]]
Micro 0.14619687646462967 and Macro 0.0958200820405762
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   523    151     47]
 [  8260  12217   1648]
 [502463 538130 259415]]
Micro 0.20573321016529414 and Macro 0.12568618715423582
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   491    217     13]
 [  9296  12151    678]
 [527833 618773 153402]]
Micro 0.1255195206727273 and Macro 0.08333903889063947
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   523    168     33]
 [  8186  12126   1813]
 [502699 559785 237524]]
Micro 0.18911567917015973 and Macro 0.11715135884604443
----------------------------------
---------------------
Overall Micro: 0.1626386095071924
Overall Macro: 0.10328032730465997


## 2.3 Count columns + frequencies

In [10]:
nb = MultinomialNB()

In [11]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[      5     252     464]
 [     20    2136   19969]
 [    370   55194 1244450]]
Micro 0.9423453729041622 and Macro 0.3443090733556033
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[     59     349     313]
 [    152    7290   14683]
 [   2676  236775 1060563]]
Micro 0.8072751462739821 and Macro 0.32676551688607186
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[     52     261     408]
 [    155    3832   18138]
 [   2969  107168 1189871]]
Micro 0.9024087314246318 and Macro 0.3442813939048715
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[     89     274     358]
 [    291    4601   17233]
 [   5486  119147 1175375]]
Micro 0.8920598947427305 and Macro 0.34431233093567
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[     63     236     425]
 [    237    3001   18887]
 [   4395   79617 1215996]]
Micro 0.9215357366669263 and Macro 0.3465569892205916
----------------------------------
---------------------
Overall Micro: 0.8931249764024866
Overall Macro: 0.3412450608605616


## 2.4 Scaled count columns + frequencies

In [10]:
nb = MultinomialNB()

In [11]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb,scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   607    106      8]
 [ 12384   9466    275]
 [728215 504643  67156]]
Micro 0.05838032747229488 and Macro 0.045051781558025326
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    700       7      14]
 [  21137     609     379]
 [1174238   27168   98608]]
Micro 0.0755310463692303 and Macro 0.055513986118205995
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    702       5      14]
 [  20868     766     491]
 [1174801   25724   99483]]
Micro 0.07631303227718252 and Macro 0.05826716215804837
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    672      36      13]
 [  19277    2314     534]
 [1031945  154583  113480]]
Micro 0.08804146186956384 and Macro 0.0625428049285328
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    712       3       9]
 [  20999     760     366]
 [1199488   24891   75629]]
Micro 0.05828369959867166 and Macro 0.04763447644125607
----------------------------------
---------------------
Overall Micro: 0.07130991351738865
Overall Macro: 0.05380204224081371


# 3. XGBoost

## 3.1 Count columns

In [12]:
xg = xgb.XGBRFClassifier(random_state=42)

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   418    145    158]
 [  2569   8136  11420]
 [111557 274339 914118]]
Micro 0.6974827268191646 and Macro 0.294021766647766
----------------------------------
[[   313    206    202]
 [  2257  14880   4988]
 [ 85251 641278 573485]]
Micro 0.4450040064708284 and Macro 0.22048280812260967
----------------------------------
[[   411    129    181]
 [  3372   7563  11190]
 [157933 242495 899580]]
Micro 0.6860575694672276 and Macro 0.29145114515292114
----------------------------------
[[   462    168     91]
 [  3733  14406   3986]
 [157579 623263 519166]]
Micro 0.4036983673179353 and Macro 0.20627940260670038
----------------------------------
[[   305    177    242]
 [  2182  12497   7446]
 [ 77677 512335 709996]]
Micro 0.5463916356794423 and Macro 0.252331139244665
----------------------------------
---------------------
Overall Micro: 0.5557268611509196
Overall Macro: 0.25291325235493245


## 3.2 Scaled Count columns

In [12]:
xg = xgb.XGBRFClassifier(random_state=42)

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   536    109     76]
 [  6557  11894   3674]
 [271317 538271 490426]]
Micro 0.3801279046913506 and Macro 0.19736042032725143
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   512    127     82]
 [  5726  12118   4281]
 [214905 565821 519288]]
Micro 0.40209697171280406 and Macro 0.20483175045288785
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   482    149     90]
 [  5244  13276   3605]
 [227160 593450 479398]]
Micro 0.37279699800582683 and Macro 0.19468409848950927
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   513    128     80]
 [  5323  13522   3280]
 [198985 671297 429726]]
Micro 0.33545727646437173 and Macro 0.17971523965192712
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   523    124     77]
 [  6319  11379   4427]
 [258568 519226 522214]]
Micro 0.4037594388509113 and Macro 0.2056145026202596
----------------------------------
---------------------
Overall Micro: 0.3788477179450529
Overall Macro: 0.19644120230836706


## 3.3 Count columns + frequencies

In [14]:
xg = xgb.XGBRFClassifier(random_state=42)

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg)

[[   455    118    148]
 [  3495  12505   6125]
 [137428 503835 658751]]
Micro 0.5077717974691199 and Macro 0.24110405551174452
----------------------------------
[[   341    174    206]
 [  3037  14040   5048]
 [117256 599389 583369]]
Micro 0.4518618750283477 and Macro 0.22251897127144057
----------------------------------
[[   460    118    143]
 [  3710   8520   9895]
 [158595 310034 831379]]
Micro 0.6352620924153384 and Macro 0.2773668364070212
----------------------------------
[[   438    142    141]
 [  3652  13828   4645]
 [137203 610125 552680]]
Micro 0.4285779080684641 and Macro 0.21468423806391532
----------------------------------
[[   361    154    209]
 [  3104  12105   6916]
 [114657 501254 684097]]
Micro 0.5265595601036241 and Macro 0.24612783409263558
----------------------------------
---------------------
Overall Micro: 0.5100066466169789
Overall Macro: 0.24036038706935145


## 3.4 Scaled Count columns + frequencies

In [14]:
xg = xgb.XGBRFClassifier(random_state=42)

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   528    102     91]
 [  5966  11875   4284]
 [236299 521179 542536]]
Micro 0.419499417927823 and Macro 0.21153652423263528
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   509    130     82]
 [  5593  12386   4146]
 [203581 562876 533557]]
Micro 0.4130837730372073 and Macro 0.20898145833274107
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   472    156     93]
 [  4897  13592   3636]
 [202322 615011 482675]]
Micro 0.3755055357582923 and Macro 0.19555969630305703
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   512    112     97]
 [  5157  12629   4339]
 [188323 582655 529030]]
Micro 0.4098494618453738 and Macro 0.20774687786949253
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   503    134     87]
 [  5598  12345   4182]
 [207279 572519 520210]]
Micro 0.40295965474726286 and Macro 0.20520643670602798
----------------------------------
---------------------
Overall Micro: 0.4041795686631919
Overall Macro: 0.20580619868879077


# 4. Random Forest

## 4.1 Count encoded columns

In [16]:
rf = RandomForestClassifier(random_state=42)

In [17]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf)

[[   415    175    131]
 [  3245  13955   4925]
 [143219 601574 555221]]
Micro 0.43057541992349907 and Macro 0.21543318501085232
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   412    168    141]
 [  3054  13701   5370]
 [139058 564637 596319]]
Micro 0.4614486793765024 and Macro 0.2261566669565688
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   420    132    169]
 [  3208   8024  10893]
 [159553 288631 851824]]
Micro 0.6503121281713629 and Macro 0.28103889954516786
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   443    165    113]
 [  3498  13957   4670]
 [147989 599101 552918]]
Micro 0.42885911823980577 and Macro 0.21500258496953661
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   408    162    154]
 [  3369  11311   7445]
 [141767 473386 684855]]
Micro 0.5265678754392954 and Macro 0.24588184066977262
----------------------------------
---------------------
Overall Micro: 0.4995526442300931
Overall Macro: 0.23670263543037967


## 4.2 Scaled Count encoded columns

In [16]:
rf = RandomForestClassifier(random_state=42)

In [17]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   443    190     88]
 [  5172  13325   3628]
 [256915 634441 408658]]
Micro 0.31932782002630666 and Macro 0.17347765128419987
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   525    123     73]
 [  6000  13212   2913]
 [275060 671598 353356]]
Micro 0.2774995086403701 and Macro 0.15591928558273385
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   478    165     78]
 [  4701  14110   3314]
 [237274 636569 426165]]
Micro 0.3331834049713725 and Macro 0.17955504500244965
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   499    128     94]
 [  4782  13171   4172]
 [196342 662284 441382]]
Micro 0.34399260991764774 and Macro 0.182793029045035
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   522    154     48]
 [  6948  13635   1542]
 [361502 685727 252779]]
Micro 0.20178749479346597 and Macro 0.1219536026471169
----------------------------------
---------------------
Overall Micro: 0.2951581676698326
Overall Macro: 0.16273972271230705


## 4.3 Count columns + frequencies

In [18]:
rf = RandomForestClassifier(random_state=42)

In [19]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   464    128    129]
 [  4119  12334   5672]
 [193147 528240 578627]]
Micro 0.44708056786054456 and Macro 0.22087153378667138
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   470    139    112]
 [  4661  10967   6497]
 [202799 473398 623817]]
Micro 0.48021256973527054 and Macro 0.23136476125551333
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   489    107    125]
 [  4709   8051   9365]
 [219392 314051 766565]]
Micro 0.585933897467143 and Macro 0.2631943064525694
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   485    125    111]
 [  4566  12370   5189]
 [191984 550016 558008]]
Micro 0.43153893022208045 and Macro 0.2153875921187209
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   459    137    128]
 [  4347  11169   6609]
 [189849 483172 626987]]
Micro 0.4827543717877291 and Macro 0.2321374163050839
----------------------------------
---------------------
Overall Micro: 0.4855040674145535
Overall Macro: 0.2325911219837118


## 4.4 scaled Count columns + frequencies

In [18]:
rf = RandomForestClassifier(random_state=42)

In [19]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   452    147    122]
 [  4517  12340   5268]
 [182408 547572 570034]]
Micro 0.4405802579260088 and Macro 0.2183641213055881
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   467     90    164]
 [  3967   6432  11726]
 [159033 221775 919206]]
Micro 0.7000778616028908 and Macro 0.29368258069917774
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   454    177     90]
 [  3738  13662   4725]
 [177989 591455 530564]]
Micro 0.41174611861928834 and Macro 0.2088879034158716
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   466    139    116]
 [  4001  13276   4848]
 [154232 597830 547946]]
Micro 0.4246031686036403 and Macro 0.21306971713658837
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   464    142    118]
 [  4411  12255   5459]
 [162067 608211 529730]]
Micro 0.4100586835916505 and Macro 0.20697738253533526
----------------------------------
---------------------
Overall Micro: 0.47741321806869574
Overall Macro: 0.22819634101851224


# 5. MLPClassifier

## 5.1 Count encoded columns

In [20]:
nnet = MLPClassifier(random_state=42)

In [21]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   454    152    115]
 [  3419  14078   4628]
 [139106 574266 586642]]
Micro 0.45445020637104455 and Macro 0.22425172243964656
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   367    164    190]
 [  2469  13693   5963]
 [109402 544602 646010]]
Micro 0.4989719244666858 and Macro 0.23850105275339153
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   390    117    214]
 [  2847   8008  11270]
 [121133 267706 911169]]
Micro 0.6951386925541292 and Macro 0.29329285879180417
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   416    168    137]
 [  2942  14341   4842]
 [115978 602404 581626]]
Micro 0.45083055272917494 and Macro 0.22279844486380943
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   404    149    171]
 [  2983  11793   7349]
 [113948 477179 708881]]
Micro 0.5450914195563088 and Macro 0.2520302323013987
----------------------------------
---------------------
Overall Micro: 0.5288965591354687
Overall Macro: 0.2461748622300101


## 5.2 Scaled Count encoded columns

In [20]:
nnet = MLPClassifier(random_state=42)

In [21]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   501    211      9]
 [  8291  13332    502]
 [602649 593408 103957]]
Micro 0.08904192431549823 and Macro 0.06401962344435201
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   589    118     14]
 [  9951  11433    741]
 [619033 535057 145924]]
Micro 0.11939736631238378 and Macro 0.08126956786188247
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   446    259     16]
 [  6329  15245    551]
 [502566 688126 109316]]
Micro 0.09449795669060986 and Macro 0.066276791105206
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   609    103      9]
 [  9973  11621    531]
 [652949 531971 115088]]
Micro 0.09624493708300387 and Macro 0.06850192613253188
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   429    278     17]
 [  6101  15390    634]
 [413221 756045 130742]]
Micro 0.11079126466428343 and Macro 0.07449705839042224
----------------------------------
---------------------
Overall Micro: 0.10199468981315582
Overall Macro: 0.07091299338687893


## 5.3 Count encoded columns + frequencies

In [22]:
nnet = MLPClassifier(random_state=42)

In [23]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   520     32    169]
 [  6074   3668  12383]
 [226386 133880 939748]]
Micro 0.7135569901576887 and Macro 0.29495272296329067
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   446    184     91]
 [  4889  12439   4797]
 [206814 521476 571724]]
Micro 0.4419280951876994 and Macro 0.2194091583750238
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   258    155    308]
 [  2615   9987   9523]
 [124645 351632 823731]]
Micro 0.6304369189646023 and Macro 0.2760717324941742
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   503    128     90]
 [  5122  12725   4278]
 [201725 558103 540180]]
Micro 0.41834397446732596 and Macro 0.21114944032626393
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   416    137    171]
 [  3826  12137   6162]
 [132032 517802 650174]]
Micro 0.5009815875790051 and Macro 0.23821877091273805
----------------------------------
---------------------
Overall Micro: 0.5410495132712644
Overall Macro: 0.24796036501429816


## 5.4 Scaled Count encoded columns + frequencies

In [22]:
nnet = MLPClassifier(random_state=42)

In [23]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   542    139     40]
 [  7121  12989   2015]
 [417823 571528 310663]]
Micro 0.24507052900533693 and Macro 0.14353973171778675
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   583    115     23]
 [  8760  11566   1799]
 [457878 577257 264879]]
Micro 0.20941596238453047 and Macro 0.1261600260590956
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   472    182     67]
 [  4968  14178   2979]
 [283302 612517 404189]]
Micro 0.31661770686712215 and Macro 0.1734839987258779
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   574    121     26]
 [  8294  12786   1045]
 [498697 615309 186002]]
Micro 0.1507059735995053 and Macro 0.09724555606763234
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   496    196     32]
 [  6548  14497   1080]
 [397993 684457 217558]]
Micro 0.17579451142489325 and Macro 0.10971758777437307
----------------------------------
---------------------
Overall Micro: 0.21952093665627764
Overall Macro: 0.13002938006895315


# 6. DecisionTreeClassifier

## 6.1 Count encoded columns

In [24]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   196    323    202]
 [  2561  14662   4902]
 [140498 647926 511590]]
Micro 0.39796199144278305 and Macro 0.20291157328222179
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   204    242    275]
 [  2291  13896   5938]
 [138278 589334 572402]]
Micro 0.4433590856175257 and Macro 0.21889699113409136
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   235    188    298]
 [  2609   8233  11283]
 [164082 328125 807801]]
Micro 0.6170514659970034 and Macro 0.27033587731477304
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   242    269    210]
 [  3166  13958   5001]
 [148506 619445 532057]]
Micro 0.41293823808220703 and Macro 0.20830642629655402
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   229    219    276]
 [  2758  13698   5669]
 [142707 593332 563969]]
Micro 0.4368544748222975 and Macro 0.216619186297214
----------------------------------
---------------------
Overall Micro: 0.46163305119236336
Overall Macro: 0.22341401086497087


## 6.2 Scaled Count encoded columns

In [24]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   173    369    179]
 [  5286  13564   3275]
 [290797 695617 313600]]
Micro 0.24744644180034167 and Macro 0.14203470709924135
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   311    149    261]
 [  5470  12944   3711]
 [259156 720918 319940]]
Micro 0.2518747259725141 and Macro 0.1435371054546187
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   199    204    318]
 [  2031  12225   7869]
 [125772 665812 508424]]
Micro 0.3937305250617226 and Macro 0.19924991994870667
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   387    181    153]
 [  3718  11731   6676]
 [192142 616521 491345]]
Micro 0.3805884851994249 and Macro 0.19549494721739027
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   272    340    112]
 [  3509  14732   3884]
 [150124 819029 330855]]
Micro 0.26144851635513133 and Macro 0.14756002501728233
----------------------------------
---------------------
Overall Micro: 0.3070177388778269
Overall Macro: 0.16557534094744786


## 6.3 Only count encoded columns + frequencies

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   237    215    269]
 [  3404  12243   6478]
 [168958 553699 577357]]
Micro 0.4458801384878218 and Macro 0.2190749518488774
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   196    166    359]
 [  3670  11699   6756]
 [180905 532322 586787]]
Micro 0.45256640914382473 and Macro 0.2210281573775211
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   341    155    225]
 [  4032   8142   9951]
 [195089 345824 759095]]
Micro 0.5802439271453993 and Macro 0.2601225818424369
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   322    162    237]
 [  3137  12750   6238]
 [157812 597023 545173]]
Micro 0.4220004626360883 and Macro 0.21105629758643005
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   308    171    245]
 [  3690  11454   6981]
 [167576 516034 616398]]
Micro 0.47485102320205436 and Macro 0.22870380455324066
----------------------------------
---------------------
Overall Micro: 0.4751083921230377
Overall Macro: 0.2279971586417012


## 6.4 Scaled count encoded columns + frequencies

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   205    328    188]
 [  6057  12794   3274]
 [319475 650001 330538]]
Micro 0.2596926356530547 and Macro 0.14772297956752165
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   257    167    297]
 [  6769   6555   8801]
 [343564 363735 592715]]
Micro 0.4532051766626854 and Macro 0.2193895172576836
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   229    137    355]
 [  7609   4586   9930]
 [424297 191241 684470]]
Micro 0.5210590133151505 and Macro 0.24312710115603553
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   356    204    161]
 [  5842   9286   6997]
 [274126 486003 539879]]
Micro 0.4154056305533339 and Macro 0.2076666251116116
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   200    348    176]
 [  2823  11951   7351]
 [136700 589343 573965]]
Micro 0.4430682983875052 and Macro 0.21709370509679263
----------------------------------
---------------------
Overall Micro: 0.41848615091434593
Overall Macro: 0.20699998563792898
