In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

from helper import util_three_class

# 0. Get folder names for train and validation

In [2]:
folder_train = '/path/to/9_FINAL/data/machine_learning/count_based/three_class/train/downsampled_to_types/train_'

In [3]:
folder_validation = '/path/to/9_FINAL/data/machine_learning/count_based/three_class/validation/validation_'

# 1. Logistic Regression

## 1.1 Only count based

In [4]:
lr = LogisticRegression(random_state=42)

In [5]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    275     169     277]
 [   1060    5193   16197]
 [  30465  126288 1143261]]
Micro 0.8681544908686238 and Macro 0.33796175914417054
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    293     157     271]
 [   1119    5268   16048]
 [  30466  124166 1145382]]
Micro 0.8698375870069606 and Macro 0.3392786943548059
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    266     177     278]
 [   1072    5150   16222]
 [  32028  119979 1148001]]
Micro 0.8717053627908068 and Macro 0.3389820059839302
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    300     179     242]
 [   1180    5296   15995]
 [  30870  129736 1139402]]
Micro 0.8653249697702539 and Macro 0.3377670418447567
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    272     163     289]
 [   1109    5510   15828]
 [  31690  125598 1142720]]
Micro 0.8679868710129166 and Macro 0.33908794150977495
----------------------------------
---------------------
Overall Micro: 0.8686018562899122
Overall Macro: 0.33861548856748763


## 1.2 Scaled count based

In [4]:
lr = LogisticRegression(random_state=42)

In [5]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                lr, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    245     156     320]
 [   1067    3109   18274]
 [  35903   99013 1165098]]
Micro 0.8830601918854885 and Macro 0.3336540459055928
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    246     160     315]
 [    921    3054   18460]
 [  22685   92691 1184638]]
Micro 0.8977969573070732 and Macro 0.3393496752993676
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    213     156     352]
 [    821    3085   18538]
 [  23854  103190 1172964]]
Micro 0.8889706788152417 and Macro 0.3353154624061061
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    216     149     356]
 [    918    2385   19168]
 [  25487   64386 1210135]]
Micro 0.9165175332527208 and Macro 0.34197177733091905
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    232     182     310]
 [   1132    3807   17508]
 [  32435  127701 1139872]]
Micro 0.8645171968418484 and Macro 0.33014371610307197
----------------------------------
---------------------
Overall Micro: 0.8901725116204744
Overall Macro: 0.3360869354090115


## 1.3 Only count columns + frequencies

In [6]:
lr = LogisticRegression(random_state=42)

In [7]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   411    131    179]
 [  3086   7572  11792]
 [106843 281283 911888]]
Micro 0.695194549514996 and Macro 0.29203923239689455
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   452     88    181]
 [  3622   6151  12662]
 [108337 211913 979764]]
Micro 0.7454574997921658 and Macro 0.30461158887144607
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   416    134    171]
 [  3283   8862  10299]
 [118905 311479 869624]]
Micro 0.6642381608451805 and Macro 0.2854049776194018
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   434    126    161]
 [  3409   7554  11508]
 [107501 261490 931017]]
Micro 0.7096470677146312 and Macro 0.2966051851219057
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   417    150    157]
 [  3589   8660  10198]
 [118635 312481 868892]]
Micro 0.6635300288169628 and Macro 0.28485625897807826
----------------------------------
---------------------
Overall Micro: 0.6956134613367873
Overall Macro: 0.2927034485975453


## 1.4 Scaled count columns + frequencies

In [6]:
lr = LogisticRegression(random_state=42)

In [7]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                lr, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    400     117     204]
 [   3107    3791   15552]
 [ 133033  164850 1002131]]
Micro 0.7605300846064609 and Macro 0.3033899396297987
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   409    126    186]
 [  3105   3983  15347]
 [124319 181523 994172]]
Micro 0.7546755141062751 and Macro 0.30183617564033655
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   387    126    208]
 [  3003   3968  15473]
 [136379 187746 975883]]
Micro 0.740823762274472 and Macro 0.29808638150752315
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[    410     109     202]
 [   3148    3820   15503]
 [ 125184  158429 1016395]]
Micro 0.7713308645707376 and Macro 0.30644093919581467
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[   393    126    205]
 [  3059   4052  15336]
 [125073 183848 991087]]
Micro 0.7523789298348901 and Macro 0.3013068163887718
----------------------------------
---------------------
Overall Micro: 0.7559478310785671
Overall Macro: 0.302212050472449


# 2. Naive Bayes

## 2.1 Only count columns

In [8]:
nb = MultinomialNB()

In [9]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   348    119    254]
 [  4209   7087  11154]
 [216847 206303 876864]]
Micro 0.6683109315779728 and Macro 0.2882064656629509
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   327    133    261]
 [  4342   7134  10959]
 [222417 208777 868820]]
Micro 0.6622588178389776 and Macro 0.2865876145334494
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   321    132    268]
 [  4310   7047  11087]
 [224040 199076 876892]]
Micro 0.668287517958725 and Macro 0.2886262566296698
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   343    125    253]
 [  4310   6986  11175]
 [215235 202980 881793]]
Micro 0.67194830713422 and Macro 0.289097663989181
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   303    141    280]
 [  4352   7027  11068]
 [216654 204694 878660]]
Micro 0.6695919448540221 and Macro 0.28837776972897694
----------------------------------
---------------------
Overall Micro: 0.6680795038727835
Overall Macro: 0.2881791541088456


## 2.2 Scaled count columns

In [8]:
nb = MultinomialNB()

In [9]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nb, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   464    133    124]
 [ 13089   7210   2151]
 [617884 333440 348690]]
Micro 0.26932288379931757 and Macro 0.15452364757285755
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   407    202    112]
 [  6875  13523   2037]
 [338725 637479 323810]]
Micro 0.2552506480648745 and Macro 0.14693121962918515
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   418    195    108]
 [  7005  13505   1934]
 [335098 626440 338470]]
Micro 0.26632420703868653 and Macro 0.15194589948700565
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   424    157    140]
 [ 12695   7082   2694]
 [609273 316715 374020]]
Micro 0.2883358524788392 and Macro 0.16278075010908197
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   513    132     79]
 [ 13946   6791   1710]
 [691843 320388 287777]]
Micro 0.22300913179547135 and Macro 0.13412145707177378
----------------------------------
---------------------
Overall Micro: 0.2604485446354378
Overall Macro: 0.15006059477398084


## 2.3 Only count + frequencies

In [10]:
nb = MultinomialNB()

In [11]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    126     157     438]
 [    342    3043   19065]
 [   5709   67213 1227092]]
Micro 0.9297724807944467 and Macro 0.3552587905605545
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    136     163     422]
 [    388    3193   18854]
 [   6244   67752 1226018]]
Micro 0.9290922557192197 and Macro 0.3559811080069921
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    123     161     437]
 [    337    2982   19125]
 [   6342   61985 1231681]]
Micro 0.9332007228079775 and Macro 0.3554514356579261
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    126     180     415]
 [    346    3154   18971]
 [   5450   61887 1232671]]
Micro 0.9340621221281741 and Macro 0.35862891751622267
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    106     171     447]
 [    335    2807   19305]
 [   5189   56908 1237911]]
Micro 0.9377597437686057 and Macro 0.35651664702180846
----------------------------------
---------------------
Overall Micro: 0.9327774650436848
Overall Macro: 0.3563673797527008


## 2.4 Scaled count + frequencies

In [10]:
nb = MultinomialNB()

In [11]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nb, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   204    276    241]
 [ 11848   3818   6784]
 [739804  96098 464112]]
Micro 0.3537933093256045 and Macro 0.19562806554489712
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   201    297    223]
 [ 11795   4549   6091]
 [753281 120000 426733]]
Micro 0.3260979314827271 and Macro 0.18491982761743475
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   199    328    194]
 [ 11908   4907   5629]
 [738727 134439 426842]]
Micro 0.3264486200972964 and Macro 0.18458780674883757
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   204    211    306]
 [ 11733   2522   8216]
 [740248  53125 506635]]
Micro 0.38494634220072543 and Macro 0.20772056211619916
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   220    292    212]
 [ 11861   4155   6431]
 [762666 108849 428493]]
Micro 0.32714243499934625 and Macro 0.1852283629723689
----------------------------------
---------------------
Overall Micro: 0.3436857276211399
Overall Macro: 0.19161692499994748


# 3. XGBoost

## 3.1 Only count

In [12]:
xg = xgb.XGBRFClassifier(random_state=42)

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   466    161     94]
 [  4057  14280   4113]
 [153290 607180 539544]]
Micro 0.41890589751244156 and Macro 0.21182836959362836
----------------------------------
[[   460    171     90]
 [  4145  14070   4220]
 [143411 611955 544648]]
Micro 0.42260480512708115 and Macro 0.21290170404144423
----------------------------------
[[   454    149    118]
 [  4056  13917   4471]
 [161489 565257 573262]]
Micro 0.4441089713892288 and Macro 0.22074951403941787
----------------------------------
[[   476    140    105]
 [  4209  13778   4484]
 [146336 586947 566725]]
Micro 0.43907119105199516 and Macro 0.218725300648955
----------------------------------
[[   442    181    101]
 [  4065  13892   4490]
 [143157 595339 561512]]
Micro 0.4351988657619264 and Macro 0.21724277774662967
----------------------------------
---------------------
Overall Micro: 0.43197794616853463
Overall Macro: 0.21628953321401503


## 3.2 Scaled count

In [12]:
xg = xgb.XGBRFClassifier(random_state=42)

In [13]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                xg, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   512    127     82]
 [  5675  13076   3699]
 [211407 601625 486982]]
Micro 0.37830688830360076 and Macro 0.19653512892551753
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   384    230    107]
 [  2213  15192   5030]
 [ 69202 687119 543693]]
Micro 0.4226735793586614 and Macro 0.21354808715987741
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   496    122    103]
 [  5597  12359   4488]
 [216204 548581 535223]]
Micro 0.41421492125368337 and Macro 0.20954322068991327
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   479    142    100]
 [  4192  13858   4421]
 [150185 599486 550337]]
Micro 0.4267487908101572 and Macro 0.2143791356428324
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   496    155     73]
 [  5658  12833   3956]
 [198674 617623 483711]]
Micro 0.37564078631840436 and Macro 0.19508910413994873
----------------------------------
---------------------
Overall Micro: 0.4035169932089014
Overall Macro: 0.20581893531161785


## 3.3 Only count + frequencies

In [14]:
xg = xgb.XGBRFClassifier(random_state=42)

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg)

[[   464    124    133]
 [  3731  13149   5570]
 [134759 535070 630185]]
Micro 0.48655176713762627 and Macro 0.2345890858171397
----------------------------------
[[   460    139    122]
 [  3839  13168   5428]
 [134102 549887 616025]]
Micro 0.47586704656242207 and Macro 0.23091514380232028
----------------------------------
[[   455    137    129]
 [  3664  13374   5406]
 [143589 531434 624985]]
Micro 0.48278947650836285 and Macro 0.23358295143387328
----------------------------------
[[   476    129    116]
 [  3808  13506   5157]
 [126638 570868 602502]]
Micro 0.46590386940749695 and Macro 0.2277865681548169
----------------------------------
[[   448    164    112]
 [  3600  13662   5185]
 [117000 585138 597870]]
Micro 0.4625073402767124 and Macro 0.22653861779401976
----------------------------------
---------------------
Overall Micro: 0.47472389997852416
Overall Macro: 0.23068247340043396


## 3.4 Scaled count + frequencies

In [14]:
xg = xgb.XGBRFClassifier(random_state=42)

In [15]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                xg, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   507    119     95]
 [  5491  12669   4290]
 [202228 558568 539218]]
Micro 0.4174729913050707 and Macro 0.21082668132263316
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   405    178    138]
 [  2558  14242   5635]
 [ 82488 621666 595860]]
Micro 0.4613972505422584 and Macro 0.22644404404054377
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   491    115    115]
 [  5390  12009   5045]
 [209644 510390 579974]]
Micro 0.44776760106199265 and Macro 0.22130830751764816
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   476    129    116]
 [  3706  13601   5164]
 [127587 579182 593239]]
Micro 0.45897521160822247 and Macro 0.2254451391108505
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   494    153     77]
 [  5623  12749   4075]
 [196702 609417 493889]]
Micro 0.38326787229845705 and Macro 0.19792038098232564
----------------------------------
---------------------
Overall Micro: 0.4337761853632003
Overall Macro: 0.21638891059480025


# 4. Random Forest

## 4.1 Only count

In [16]:
rf = RandomForestClassifier(random_state=42)

In [17]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf)

[[   100    453    168]
 [   667  16751   5032]
 [ 35105 634555 630354]]
Micro 0.4891266149480231 and Macro 0.2354979458664773
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   115    446    160]
 [   711  16739   4985]
 [ 36348 635441 628225]]
Micro 0.48752541245644926 and Macro 0.23517761919009897
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   112    435    174]
 [   725  16489   5230]
 [ 40561 610657 648790]]
Micro 0.50287528539352 and Macro 0.2400155051891372
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   102    466    153]
 [   673  16735   5063]
 [ 33863 640807 625338]]
Micro 0.48531967956469163 and Macro 0.23426178171065612
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   104    458    162]
 [   761  16498   5188]
 [ 37744 629630 632634]]
Micro 0.49066377262637934 and Macro 0.23582762762908915
----------------------------------
---------------------
Overall Micro: 0.4911021529978127
Overall Macro: 0.23615609591709177


## 4.2 Scaled count

In [16]:
rf = RandomForestClassifier(random_state=42)

In [17]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                rf, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    64    526    131]
 [  1037  17165   4248]
 [ 56078 693438 550498]]
Micro 0.4290609400801853 and Macro 0.21419079533442162
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    44    530    147]
 [   389  16641   5405]
 [ 24627 679155 596232]]
Micro 0.4632186340379543 and Macro 0.2255791074714347
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    66    519    136]
 [  1321  16311   4812]
 [ 73491 656113 570404]]
Micro 0.4434650646589675 and Macro 0.21899073304393082
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    67    509    145]
 [   659  16989   4823]
 [ 40980 676739 582289]]
Micro 0.45295117896009673 and Macro 0.22254619634700593
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    65    550    109]
 [  1277  16705   4465]
 [ 70325 699273 530410]]
Micro 0.41353437441192764 and Macro 0.20837104610132395
----------------------------------
---------------------
Overall Micro: 0.44044603842982627
Overall Macro: 0.21793557565962338


## 4.3 Count + frequencies

In [18]:
rf = RandomForestClassifier(random_state=42)

In [19]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    89    454    178]
 [   617  16484   5349]
 [ 29161 616795 654058]]
Micro 0.5068308664321316 and Macro 0.24120135120881733
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   116    436    169]
 [   569  16657   5209]
 [ 29805 628888 641321]]
Micro 0.49736163909399395 and Macro 0.23871641740153493
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   112    415    194]
 [   512  16400   5532]
 [ 27717 603454 668837]]
Micro 0.517958724973983 and Macro 0.24539725608554205
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   104    457    160]
 [   504  16624   5343]
 [ 25497 631259 643252]]
Micro 0.4987756952841596 and Macro 0.23916066005480838
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    92    458    174]
 [   602  16457   5388]
 [ 28749 623128 648131]]
Micro 0.5023356628241531 and Macro 0.2397573707233069
----------------------------------
---------------------
Overall Micro: 0.5046525177216843
Overall Macro: 0.24084661109480193


## 4.4 Scaled count + frequencies

In [18]:
rf = RandomForestClassifier(random_state=42)

In [19]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class','id', 'pids'],
                rf, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    23    534    164]
 [   199  17021   5230]
 [ 11074 666199 622741]]
Micro 0.48351893348246844 and Macro 0.23265969329012223
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    25    552    144]
 [   222  16295   5918]
 [  8205 668400 623409]]
Micro 0.48348209224816163 and Macro 0.2325648852647246
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    47    529    145]
 [   377  15839   6228]
 [ 18494 628511 653003]]
Micro 0.505518930631142 and Macro 0.2395985784963506
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    51    506    164]
 [   392  16632   5447]
 [ 25744 636526 637738]]
Micro 0.49457451632406285 and Macro 0.2364380369019626
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    32    539    153]
 [   327  16287   5833]
 [ 14187 644195 641626]]
Micro 0.4972456485479289 and Macro 0.23691107440977102
----------------------------------
---------------------
Overall Micro: 0.4928680242467528
Overall Macro: 0.23563445367258623


# 5. MLPClassifier

## 5.1 Only count columns

In [20]:
nnet = MLPClassifier(random_state=42)

In [21]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   262    294    165]
 [  1829  15611   5010]
 [ 74008 586116 639890]]
Micro 0.495594342438888 and Macro 0.23825883660353186
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   282    289    150]
 [  1896  15571   4968]
 [ 74745 587684 637585]]
Micro 0.4938428168716038 and Macro 0.2377993472802534
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   226    312    183]
 [  1307  16283   4854]
 [ 60404 596507 643097]]
Micro 0.4985032191557718 and Macro 0.23955682585428037
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   244    321    156]
 [  1451  16232   4788]
 [ 59529 620644 619835]]
Micro 0.4808879987908102 and Macro 0.23371542347096186
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    215     258     251]
 [   1778    8233   12436]
 [  74503  197968 1027537]]
Micro 0.7829515129850156 and Macro 0.31855055023116746
----------------------------------
---------------------
Overall Micro: 0.5503559780484178
Overall Macro: 0.253576196688039


## 5.2 Scaled count columns

In [20]:
nnet = MLPClassifier(random_state=42)

In [21]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                nnet, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   415    226     80]
 [  3559  15249   3642]
 [176726 615755 507533]]
Micro 0.3954072937646663 and Macro 0.203882627911152
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   361    240    120]
 [  2278  14998   5159]
 [122569 583345 594100]]
Micro 0.46060521323790593 and Macro 0.22653433352823757
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   420    146    155]
 [  4670   8237   9537]
 [208595 263035 828378]]
Micro 0.632596795732682 and Macro 0.27828637323000116
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   364    172    185]
 [  2759   7905  11807]
 [113308 221909 964791]]
Micro 0.7353839177750907 and Macro 0.30544646337279296
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   417    222     85]
 [  4428  13907   4112]
 [205466 576332 518210]]
Micro 0.40246557721971093 and Macro 0.20601308086402761
----------------------------------
---------------------
Overall Micro: 0.5252917595460113
Overall Macro: 0.24403257578124227


## 5.3 Only count + frequencies

In [22]:
nnet = MLPClassifier(random_state=42)

In [23]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   308    243    170]
 [  1976  15484   4990]
 [ 68381 588351 643282]]
Micro 0.4980966380362534 and Macro 0.23945211109940132
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   316    255    150]
 [  2427  15156   4852]
 [ 93444 572648 633922]]
Micro 0.49078652025061026 and Macro 0.23668634332953822
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   315    236    170]
 [  1981  15636   4827]
 [ 76263 587132 636613]]
Micro 0.4931811637631663 and Macro 0.2379003425558326
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   321    253    147]
 [  1776  15584   5111]
 [ 60641 593291 646076]]
Micro 0.500287938331318 and Macro 0.24055028870063241
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   283    278    163]
 [  1619  16080   4748]
 [ 57263 623806 618939]]
Micro 0.4801330734541585 and Macro 0.23380710132525384
----------------------------------
---------------------
Overall Micro: 0.49249706676710137
Overall Macro: 0.2376792374021317


## 5.4 Scaled count + frequencies

In [22]:
nnet = MLPClassifier(random_state=42)

In [23]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                nnet, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   433    247     41]
 [  4236  16014   2200]
 [227725 723457 348832]]
Micro 0.2760604148323931 and Macro 0.156095144316763
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   249    401     71]
 [  1270  17514   3651]
 [ 84175 713989 501850]]
Micro 0.3927031296054173 and Macro 0.20269475196553868
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   417    223     81]
 [  4104  14961   3379]
 [204906 632776 462326]]
Micro 0.3610291322449899 and Macro 0.1907493354666161
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   327    289    105]
 [  1999  16526   3946]
 [101123 677374 521511]]
Micro 0.4068651753325272 and Macro 0.20791271864412772
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/linda/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[   408    244     72]
 [  4760  14587   3100]
 [240821 652461 406726]]
Micro 0.3187180268126988 and Macro 0.1737779069276059
----------------------------------
---------------------
Overall Micro: 0.35107517576560526
Overall Macro: 0.1862459714641303


# 6. DecisionTreeClassifier

## 6.1 Only count columns

In [24]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    99    389    233]
 [   909  16105   5436]
 [ 47015 651743 601256]]
Micro 0.4666467651915643 and Macro 0.22709826935332067
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   126    403    192]
 [   988  16024   5423]
 [ 47729 651403 600882]]
Micro 0.4663285896747961 and Macro 0.2272867162753075
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   137    358    226]
 [   997  15789   5658]
 [ 53260 629037 617711]]
Micro 0.4788769117870452 and Macro 0.23150465544174206
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   113    395    213]
 [   925  16111   5435]
 [ 46673 657835 595500]]
Micro 0.4623065296251512 and Macro 0.22578977250532906
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   124    394    206]
 [  1003  15807   5637]
 [ 49426 646076 604506]]
Micro 0.4688987657754544 and Macro 0.22795972977119572
----------------------------------
---------------------
Overall Micro: 0.46861151241080223
Overall Macro: 0.22792782866937902


## 6.2 Scaled count columns

In [24]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'frequency', 'pidspread', 
                 'pldspread', 'id', 'pids'],
                dt, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    81    433    207]
 [  1162  16282   5006]
 [ 66245 687263 546506]]
Micro 0.42538949579990704 and Macro 0.21248899451054423
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    76    436    209]
 [   548  15954   5933]
 [ 30662 686735 582617]]
Micro 0.45243392761323187 and Macro 0.22188415521397917
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   129    382    210]
 [  1694  15330   5420]
 [ 87046 645603 567359]]
Micro 0.4404699914523649 and Macro 0.217850089189168
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    90    422    209]
 [   890  16372   5209]
 [ 49303 689770 560935]]
Micro 0.4363641172914148 and Macro 0.21651450606755385
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    85    450    189]
 [  1558  15773   5116]
 [ 80687 682221 537100]]
Micro 0.41790113053487093 and Macro 0.2096154463991151
----------------------------------
---------------------
Overall Micro: 0.4345117325383579
Overall Macro: 0.21567063827607208


## 6.3 Only count columns + frequencies

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   120    354    247]
 [   873  15638   5939]
 [ 38401 635700 625913]]
Micro 0.4849442821676485 and Macro 0.2334272516771556
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   125    394    202]
 [   873  15751   5811]
 [ 40252 643446 616316]]
Micro 0.47778592319958885 and Macro 0.2311195671345855
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   127    350    244]
 [   804  15629   6011]
 [ 38176 626122 635710]]
Micro 0.49235134030092814 and Macro 0.236039803062407
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   125    371    225]
 [   800  15790   5881]
 [ 34445 650698 614865]]
Micro 0.4767079806529625 and Macro 0.2309658321523368
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   108    393    223]
 [   850  15598   5999]
 [ 37520 641574 620914]]
Micro 0.4811291593956676 and Macro 0.23192444706695714
----------------------------------
---------------------
Overall Micro: 0.48258373714335906
Overall Macro: 0.2326953802186884


## 6.4 Scaled count columns + frequencies

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
util_three_class.cross_validation(folder_validation, folder_train,
                ['instance', 'class', 'id', 'pids'],
                dt, scale=True)

/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    67    414    240]
 [   712  15637   6101]
 [ 32445 676691 590878]]
Micro 0.45842569255243976 and Macro 0.22351987928176398
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    83    449    189]
 [   525  15086   6824]
 [ 22338 656862 620814]]
Micro 0.48065101234157365 and Macro 0.23149615714683658
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[   131    382    208]
 [   849  14465   7130]
 [ 39098 616054 644856]]
Micro 0.498386832258518 and Macro 0.23711543213644318
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    79    404    238]
 [   788  15551   6132]
 [ 40971 654784 604253]]
Micro 0.46847264207980654 and Macro 0.227031940101461
----------------------------------


/home/linda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


[[    69    385    270]
 [   682  15442   6323]
 [ 29513 667582 602913]]
Micro 0.4673774296599326 and Macro 0.22656349924778477
----------------------------------
---------------------
Overall Micro: 0.4746627217784541
Overall Macro: 0.2291453815828579
